/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Disease = IDL.Record({
  'fertilizers' : IDL.Vec(IDL.Text),
  'severityLevel' : IDL.Text,
  'name' : IDL.Text,
  'treatment' : IDL.Text,
  'description' : IDL.Text,
  'quickActions' : IDL.Vec(IDL.Text),
  'yieldImpact' : IDL.Text,
  'seasonalAdvice' : IDL.Text,
  'preventionTips' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getAllDiseases' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat32, Disease))],
      ['query'],
    ),
  'getDisease' : IDL.Func([IDL.Nat32], [Disease], ['query']),
  'simulateDetection' : IDL.Func(
      [IDL.Text, IDL.Nat32],
      [IDL.Opt(IDL.Nat32)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Disease = IDL.Record({
    'fertilizers' : IDL.Vec(IDL.Text),
    'severityLevel' : IDL.Text,
    'name' : IDL.Text,
    'treatment' : IDL.Text,
    'description' : IDL.Text,
    'quickActions' : IDL.Vec(IDL.Text),
    'yieldImpact' : IDL.Text,
    'seasonalAdvice' : IDL.Text,
    'preventionTips' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getAllDiseases' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat32, Disease))],
        ['query'],
      ),
    'getDisease' : IDL.Func([IDL.Nat32], [Disease], ['query']),
    'simulateDetection' : IDL.Func(
        [IDL.Text, IDL.Nat32],
        [IDL.Opt(IDL.Nat32)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };